# Generated by Django 3.0.3 on 2020-03-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200306_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('בטיפול', 'בטיפול'), ('הושלם', 'הושלם'), ('בוטל', 'בוטל')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('General', 'General')], max_length=200, null=True),
        ),
    ]
