# Generated by Django 3.0.3 on 2020-03-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200306_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Work in progress', 'Work in progress'), ('completed', 'completed')], max_length=200, null=True),
        ),
    ]
