# Generated by Django 3.0.3 on 2020-03-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200313_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_finish',
            field=models.DateTimeField(null=True, verbose_name='תאריך סיום'),
        ),
        migrations.AddField(
            model_name='order',
            name='desc',
            field=models.TextField(max_length=255, null=True, verbose_name='פרטים'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Work in progress', 'Work in progress'), ('completed', 'completed')], max_length=200, null=True, verbose_name='סטאטוס'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Order'),
        ),
        migrations.CreateModel(
            name='OrderTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200, null=True, verbose_name='משימה')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Order')),
            ],
        ),
    ]
