# Generated by Django 3.0.3 on 2020-03-14 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200314_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='product',
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='service',
            field=models.TextField(null=True, verbose_name='שרות'),
        ),
        migrations.AlterField(
            model_name='ordertask',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Order'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Order', verbose_name='הזמנה'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='כמות'),
        ),
    ]
