# Generated by Django 3.0.3 on 2020-03-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200314_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertask',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Order'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Order', verbose_name='הזמנה'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='service',
            field=models.CharField(max_length=255, null=True, verbose_name='שרות'),
        ),
    ]
